name: Cron-Build

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    container: cyberryteam/epitech-docker:ubuntu

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
      
    - name: Make test
      run: make
    - name: Make clean test
      run: make clean
    - name: Make fclean test
      run: make fclean
    - name: Make re test
      run: make re
