name: Pull Request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    container: cyberryteam/epitech-docker:ubuntu

    steps:
    - name: Make test
      run: make
    - name: Make clean test
      run: make clean
    - name: Make fclean test
      run: make fclean
    - name: Make re test
      run: make re
