name: Push

on:
  push:
    branches: [master]

env:
      REPOSITORY_OWNER: lucas.mathieux@epitech.eu
      REPOSITORY_NAME: OOP_nanotekspice_2019

jobs:

  fedora:
    runs-on: ubuntu-latest
    container: cyberryteam/epitech-docker:fedora

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make

    - name: Functional tests
      run: make tests_sh

    - name: Unit tests
      run: make tests_run

    - name: Push
      run: |
        mkdir -p ~/.ssh/
        ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git push git@git.epitech.eu:/$REPOSITORY_OWNER/$REPOSITORY_NAME HEAD:master --force

  ubuntu:
    runs-on: ubuntu-latest
    container: cyberryteam/epitech-docker:ubuntu

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make

    - name: Functional tests
      run: make tests_sh

    - name: Unit tests
      run: make tests_run
